# Generated by Django 2.2.2 on 2019-06-22 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190620_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='status',
        ),
    ]
